const resources = [
  { "name": "AI Search", "abbreviation": "srch", "provider": "Microsoft.Search", "type": "Microsoft.Search/searchServices" },
  { "name": "Azure AI Services", "abbreviation": "ais", "provider": "Microsoft.CognitiveServices", "type": "Microsoft.CognitiveServices/accounts" },
  { "name": "Azure AI Studio Hub", "abbreviation": "hub", "provider": "Microsoft.MachineLearningServices", "type": "Microsoft.MachineLearningServices/workspaces" },
  { "name": "Azure AI Studio Project", "abbreviation": "proj", "provider": "Microsoft.MachineLearningServices", "type": "Microsoft.MachineLearningServices/workspaces" },
  { "name": "Azure AI Video Indexer", "abbreviation": "avi", "provider": "Microsoft.VideoIndexer", "type": "Microsoft.VideoIndexer/accounts" },
  { "name": "Azure Machine Learning Workspace", "abbreviation": "mlw", "provider": "Microsoft.MachineLearningServices", "type": "Microsoft.MachineLearningServices/workspaces" },
  { "name": "Azure OpenAI Service", "abbreviation": "oai", "provider": "Microsoft.CognitiveServices", "type": "Microsoft.CognitiveServices/accounts" },
  { "name": "Bot Service", "abbreviation": "bot", "provider": "Microsoft.BotService", "type": "Microsoft.BotService/botServices" },
  { "name": "Computer Vision", "abbreviation": "cv", "provider": "Microsoft.CognitiveServices", "type": "Microsoft.CognitiveServices/accounts" },
  { "name": "Content Moderator", "abbreviation": "cm", "provider": "Microsoft.CognitiveServices", "type": "Microsoft.CognitiveServices/accounts" },
  { "name": "Content Safety", "abbreviation": "cs", "provider": "Microsoft.CognitiveServices", "type": "Microsoft.CognitiveServices/accounts" },
  { "name": "Custom Vision (Prediction)", "abbreviation": "cstv", "provider": "Microsoft.CognitiveServices", "type": "Microsoft.CognitiveServices/accounts" },
  { "name": "Custom Vision (Training)", "abbreviation": "cstvt", "provider": "Microsoft.CognitiveServices", "type": "Microsoft.CognitiveServices/accounts" },
  { "name": "Document Intelligence", "abbreviation": "di", "provider": "Microsoft.CognitiveServices", "type": "Microsoft.CognitiveServices/accounts" },
  { "name": "Face API", "abbreviation": "face", "provider": "Microsoft.CognitiveServices", "type": "Microsoft.CognitiveServices/accounts" },
  { "name": "Health Insights", "abbreviation": "hi", "provider": "Microsoft.CognitiveServices", "type": "Microsoft.CognitiveServices/accounts" },
  { "name": "Immersive Reader", "abbreviation": "ir", "provider": "Microsoft.CognitiveServices", "type": "Microsoft.CognitiveServices/accounts" },
  { "name": "Language Service", "abbreviation": "lang", "provider": "Microsoft.CognitiveServices", "type": "Microsoft.CognitiveServices/accounts" },
  { "name": "Speech Service", "abbreviation": "spch", "provider": "Microsoft.CognitiveServices", "type": "Microsoft.CognitiveServices/accounts" },
  { "name": "Translator", "abbreviation": "trsl", "provider": "Microsoft.CognitiveServices", "type": "Microsoft.CognitiveServices/accounts" },
  { "name": "Azure Analysis Services server", "abbreviation": "as", "provider": "Microsoft.AnalysisServices", "type": "Microsoft.AnalysisServices/servers" },
  { "name": "Azure Databricks workspace", "abbreviation": "dbw", "provider": "Microsoft.Databricks", "type": "Microsoft.Databricks/workspaces" },
  { "name": "Azure Data Explorer cluster", "abbreviation": "dec", "provider": "Microsoft.Kusto", "type": "Microsoft.Kusto/clusters" },
  { "name": "Azure Data Explorer cluster database", "abbreviation": "dedb", "provider": "Microsoft.Kusto", "type": "Microsoft.Kusto/clusters/databases" },
  { "name": "Azure Data Factory", "abbreviation": "adf", "provider": "Microsoft.DataFactory", "type": "Microsoft.DataFactory/factories" },
  { "name": "Azure Digital Twin instance", "abbreviation": "dt", "provider": "Microsoft.DigitalTwins", "type": "Microsoft.DigitalTwins/digitalTwinsInstances" },
  { "name": "Azure Stream Analytics", "abbreviation": "asa", "provider": "Microsoft.StreamAnalytics", "type": "Microsoft.StreamAnalytics/cluster" },
  { "name": "Azure Synapse Analytics private link hub", "abbreviation": "synplh", "provider": "Microsoft.Synapse", "type": "Microsoft.Synapse/privateLinkHubs" },
  { "name": "Azure Synapse Analytics SQL Dedicated Pool", "abbreviation": "syndp", "provider": "Microsoft.Synapse", "type": "Microsoft.Synapse/workspaces/sqlPools" },
  { "name": "Azure Synapse Analytics Spark Pool", "abbreviation": "synsp", "provider": "Microsoft.Synapse", "type": "Microsoft.Synapse/workspaces/bigDataPools" },
  { "name": "Azure Synapse Analytics workspaces", "abbreviation": "synw", "provider": "Microsoft.Synapse", "type": "Microsoft.Synapse/workspaces" },
  { "name": "Data Lake Store account", "abbreviation": "dls", "provider": "Microsoft.DataLakeStore", "type": "Microsoft.DataLakeStore/accounts" },
  { "name": "Data Lake Analytics account", "abbreviation": "dla", "provider": "Microsoft.DataLakeAnalytics", "type": "Microsoft.DataLakeAnalytics/accounts" },
  { "name": "Event Hubs namespace", "abbreviation": "evhns", "provider": "Microsoft.EventHub", "type": "Microsoft.EventHub/namespaces" },
  { "name": "Event hub", "abbreviation": "evh", "provider": "Microsoft.EventHub", "type": "Microsoft.EventHub/namespaces/eventHubs" },
  { "name": "Event Grid domain", "abbreviation": "evgd", "provider": "Microsoft.EventGrid", "type": "Microsoft.EventGrid/domains" },
  { "name": "Event Grid subscriptions", "abbreviation": "evgs", "provider": "Microsoft.EventGrid", "type": "Microsoft.EventGrid/eventSubscriptions" },
  { "name": "Event Grid topic", "abbreviation": "evgt", "provider": "Microsoft.EventGrid", "type": "Microsoft.EventGrid/domains/topics" },
  { "name": "Event Grid system topic", "abbreviation": "egst", "provider": "Microsoft.EventGrid", "type": "Microsoft.EventGrid/systemTopics" },
  { "name": "HDInsight - Hadoop cluster", "abbreviation": "hadoop", "provider": "Microsoft.HDInsight", "type": "Microsoft.HDInsight/clusters" },
  { "name": "HDInsight - HBase cluster", "abbreviation": "hbase", "provider": "Microsoft.HDInsight", "type": "Microsoft.HDInsight/clusters" },
  { "name": "HDInsight - Kafka cluster", "abbreviation": "kafka", "provider": "Microsoft.HDInsight", "type": "Microsoft.HDInsight/clusters" },
  { "name": "HDInsight - Spark cluster", "abbreviation": "spark", "provider": "Microsoft.HDInsight", "type": "Microsoft.HDInsight/clusters" },
  { "name": "HDInsight - Storm cluster", "abbreviation": "storm", "provider": "Microsoft.HDInsight", "type": "Microsoft.HDInsight/clusters" },
  { "name": "HDInsight - ML Services cluster", "abbreviation": "mls", "provider": "Microsoft.HDInsight", "type": "Microsoft.HDInsight/clusters" },
  { "name": "IoT hub", "abbreviation": "iot", "provider": "Microsoft.Devices", "type": "Microsoft.Devices/IotHubs" },
  { "name": "Provisioning services", "abbreviation": "provs", "provider": "Microsoft.Devices", "type": "Microsoft.Devices/provisioningServices" },
  { "name": "Provisioning services certificate", "abbreviation": "pcert", "provider": "Microsoft.Devices", "type": "Microsoft.Devices/provisioningServices/certificates" },
  { "name": "Power BI Embedded", "abbreviation": "pbi", "provider": "Microsoft.PowerBIDedicated", "type": "Microsoft.PowerBIDedicated/capacities" },
  { "name": "Time Series Insights environment", "abbreviation": "tsi", "provider": "Microsoft.TimeSeriesInsights", "type": "Microsoft.TimeSeriesInsights/environments" },
  { "name": "App Service environment", "abbreviation": "ase", "provider": "Microsoft.Web", "type": "Microsoft.Web/hostingEnvironments" },
  { "name": "App Service plan", "abbreviation": "asp", "provider": "Microsoft.Web", "type": "Microsoft.Web/serverFarms" },
  { "name": "Azure Load Testing instance", "abbreviation": "lt", "provider": "Microsoft.LoadTestService", "type": "Microsoft.LoadTestService/loadTests" },
  { "name": "Availability set", "abbreviation": "avail", "provider": "Microsoft.Compute", "type": "Microsoft.Compute/availabilitySets" },
  { "name": "Azure Arc enabled server", "abbreviation": "arcs", "provider": "Microsoft.HybridCompute", "type": "Microsoft.HybridCompute/machines" },
  { "name": "Azure Arc enabled Kubernetes cluster", "abbreviation": "arck", "provider": "Microsoft.Kubernetes", "type": "Microsoft.Kubernetes/connectedClusters" },
  { "name": "Azure Arc private link scope", "abbreviation": "pls", "provider": "Microsoft.HybridCompute", "type": "Microsoft.HybridCompute/privateLinkScopes" },
  { "name": "Azure Arc gateway", "abbreviation": "arcgw", "provider": "Microsoft.HybridCompute", "type": "Microsoft.HybridCompute/gateways" },
  { "name": "Batch accounts", "abbreviation": "ba", "provider": "Microsoft.Batch", "type": "Microsoft.Batch/batchAccounts" },
  { "name": "Cloud service", "abbreviation": "cld", "provider": "Microsoft.Compute", "type": "Microsoft.Compute/cloudServices" },
  { "name": "Communication Services", "abbreviation": "acs", "provider": "Microsoft.Communication", "type": "Microsoft.Communication/communicationServices" },
  { "name": "Disk encryption set", "abbreviation": "des", "provider": "Microsoft.Compute", "type": "Microsoft.Compute/diskEncryptionSets" },
  { "name": "Function app", "abbreviation": "func", "provider": "Microsoft.Web", "type": "Microsoft.Web/sites" },
  { "name": "Gallery", "abbreviation": "gal", "provider": "Microsoft.Compute", "type": "Microsoft.Compute/galleries" },
  { "name": "Hosting environment", "abbreviation": "host", "provider": "Microsoft.Web", "type": "Microsoft.Web/hostingEnvironments" },
  { "name": "Image template", "abbreviation": "it", "provider": "Microsoft.VirtualMachineImages", "type": "Microsoft.VirtualMachineImages/imageTemplates" },
  { "name": "Managed disk (OS)", "abbreviation": "osdisk", "provider": "Microsoft.Compute", "type": "Microsoft.Compute/disks" },
  { "name": "Managed disk (data)", "abbreviation": "disk", "provider": "Microsoft.Compute", "type": "Microsoft.Compute/disks" },
  { "name": "Notification Hubs", "abbreviation": "ntf", "provider": "Microsoft.NotificationHubs", "type": "Microsoft.NotificationHubs/namespaces/notificationHubs" },
  { "name": "Notification Hubs namespace", "abbreviation": "ntfns", "provider": "Microsoft.NotificationHubs", "type": "Microsoft.NotificationHubs/namespaces" },
  { "name": "Proximity placement group", "abbreviation": "ppg", "provider": "Microsoft.Compute", "type": "Microsoft.Compute/proximityPlacementGroups" },
  { "name": "Restore point collection", "abbreviation": "rpc", "provider": "Microsoft.Compute", "type": "Microsoft.Compute/restorePointCollections" },
  { "name": "Snapshot", "abbreviation": "snap", "provider": "Microsoft.Compute", "type": "Microsoft.Compute/snapshots" },
  { "name": "Static web app", "abbreviation": "stapp", "provider": "Microsoft.Web", "type": "Microsoft.Web/staticSites" },
  { "name": "Virtual machine", "abbreviation": "vm", "provider": "Microsoft.Compute", "type": "Microsoft.Compute/virtualMachines" },
  { "name": "Virtual machine scale set", "abbreviation": "vmss", "provider": "Microsoft.Compute", "type": "Microsoft.Compute/virtualMachineScaleSets" },
  { "name": "Virtual machine maintenance configuration", "abbreviation": "mc", "provider": "Microsoft.Maintenance", "type": "Microsoft.Maintenance/maintenanceConfigurations" },
  { "name": "VM storage account", "abbreviation": "stvm", "provider": "Microsoft.Storage", "type": "Microsoft.Storage/storageAccounts" },
  { "name": "Web app", "abbreviation": "app", "provider": "Microsoft.Web", "type": "Microsoft.Web/sites" },
  { "name": "AKS cluster", "abbreviation": "aks", "provider": "Microsoft.ContainerService", "type": "Microsoft.ContainerService/managedClusters" },
  { "name": "AKS system node pool", "abbreviation": "npsystem", "provider": "Microsoft.ContainerService", "type": "Microsoft.ContainerService/managedClusters/agentPools" },
  { "name": "AKS user node pool", "abbreviation": "np", "provider": "Microsoft.ContainerService", "type": "Microsoft.ContainerService/managedClusters/agentPools" },
  { "name": "Container apps", "abbreviation": "ca", "provider": "Microsoft.App", "type": "Microsoft.App/containerApps" },
  { "name": "Container apps environment", "abbreviation": "cae", "provider": "Microsoft.App", "type": "Microsoft.App/managedEnvironments" },
  { "name": "Container registry", "abbreviation": "cr", "provider": "Microsoft.ContainerRegistry", "type": "Microsoft.ContainerRegistry/registries" },
  { "name": "Container instance", "abbreviation": "ci", "provider": "Microsoft.ContainerInstance", "type": "Microsoft.ContainerInstance/containerGroups" },
  { "name": "Service Fabric cluster", "abbreviation": "sf", "provider": "Microsoft.ServiceFabric", "type": "Microsoft.ServiceFabric/clusters" },
  { "name": "Service Fabric managed cluster", "abbreviation": "sfmc", "provider": "Microsoft.ServiceFabric", "type": "Microsoft.ServiceFabric/managedClusters" },
  { "name": "Azure Cosmos DB database", "abbreviation": "cosmos", "provider": "Microsoft.DocumentDB", "type": "Microsoft.DocumentDB/databaseAccounts/sqlDatabases" },
  { "name": "Azure Cosmos DB for Apache Cassandra account", "abbreviation": "coscas", "provider": "Microsoft.DocumentDB", "type": "Microsoft.DocumentDB/databaseAccounts" },
  { "name": "Azure Cosmos DB for MongoDB account", "abbreviation": "cosmon", "provider": "Microsoft.DocumentDB", "type": "Microsoft.DocumentDB/databaseAccounts" },
  { "name": "Azure Cosmos DB for NoSQL account", "abbreviation": "cosno", "provider": "Microsoft.DocumentDB", "type": "Microsoft.DocumentDB/databaseAccounts" },
  { "name": "Azure Cosmos DB for Table account", "abbreviation": "costab", "provider": "Microsoft.DocumentDB", "type": "Microsoft.DocumentDB/databaseAccounts" },
  { "name": "Azure Cosmos DB for Apache Gremlin account", "abbreviation": "cosgrm", "provider": "Microsoft.DocumentDB", "type": "Microsoft.DocumentDB/databaseAccounts" },
  { "name": "Azure Cosmos DB PostgreSQL cluster", "abbreviation": "cospos", "provider": "Microsoft.DBforPostgreSQL", "type": "Microsoft.DBforPostgreSQL/serverGroupsv2" },
  { "name": "Azure Cache for Redis instance", "abbreviation": "redis", "provider": "Microsoft.Cache", "type": "Microsoft.Cache/Redis" },
  { "name": "Azure SQL Database server", "abbreviation": "sql", "provider": "Microsoft.Sql", "type": "Microsoft.Sql/servers" },
  { "name": "Azure SQL database", "abbreviation": "sqldb", "provider": "Microsoft.Sql", "type": "Microsoft.Sql/servers/databases" },
  { "name": "Azure SQL Elastic Job agent", "abbreviation": "sqlja", "provider": "Microsoft.Sql", "type": "Microsoft.Sql/servers/jobAgents" },
  { "name": "Azure SQL Elastic Pool", "abbreviation": "sqlep", "provider": "Microsoft.Sql", "type": "Microsoft.Sql/servers/elasticpool" },
  { "name": "MariaDB server", "abbreviation": "maria", "provider": "Microsoft.DBforMariaDB", "type": "Microsoft.DBforMariaDB/servers" },
  { "name": "MariaDB database", "abbreviation": "mariadb", "provider": "Microsoft.DBforMariaDB", "type": "Microsoft.DBforMariaDB/servers/databases" },
  { "name": "MySQL database", "abbreviation": "mysql", "provider": "Microsoft.DBforMySQL", "type": "Microsoft.DBforMySQL/servers" },
  { "name": "PostgreSQL database", "abbreviation": "psql", "provider": "Microsoft.DBforPostgreSQL", "type": "Microsoft.DBforPostgreSQL/servers" },
  { "name": "SQL Server Stretch Database", "abbreviation": "sqlstrdb", "provider": "Microsoft.Sql", "type": "Microsoft.Sql/servers/databases" },
  { "name": "SQL Managed Instance", "abbreviation": "sqlmi", "provider": "Microsoft.Sql", "type": "Microsoft.Sql/managedInstances" },
  { "name": "App Configuration store", "abbreviation": "appcs", "provider": "Microsoft.AppConfiguration", "type": "Microsoft.AppConfiguration/configurationStores" },
  { "name": "Maps account", "abbreviation": "map", "provider": "Microsoft.Maps", "type": "Microsoft.Maps/accounts" },
  { "name": "SignalR", "abbreviation": "sigr", "provider": "Microsoft.SignalRService", "type": "Microsoft.SignalRService/SignalR" },
  { "name": "WebPubSub", "abbreviation": "wps", "provider": "Microsoft.SignalRService", "type": "Microsoft.SignalRService/webPubSub" },
  { "name": "API management service instance", "abbreviation": "apim", "provider": "Microsoft.ApiManagement", "type": "Microsoft.ApiManagement/service" },
  { "name": "Integration account", "abbreviation": "ia", "provider": "Microsoft.Logic", "type": "Microsoft.Logic/integrationAccounts" },
  { "name": "Logic app", "abbreviation": "logic", "provider": "Microsoft.Logic", "type": "Microsoft.Logic/workflows" },
  { "name": "Service Bus namespace", "abbreviation": "sbns", "provider": "Microsoft.ServiceBus", "type": "Microsoft.ServiceBus/namespaces" },
  { "name": "Service Bus queue", "abbreviation": "sbq", "provider": "Microsoft.ServiceBus", "type": "Microsoft.ServiceBus/namespaces/queues" },
  { "name": "Service Bus topic", "abbreviation": "sbt", "provider": "Microsoft.ServiceBus", "type": "Microsoft.ServiceBus/namespaces/topics" },
  { "name": "Service Bus topic subscription", "abbreviation": "sbts", "provider": "Microsoft.ServiceBus", "type": "Microsoft.ServiceBus/namespaces/topics/subscriptions" },
  { "name": "Automation account", "abbreviation": "aa", "provider": "Microsoft.Automation", "type": "Microsoft.Automation/automationAccounts" },
  { "name": "Azure Policy definition", "abbreviation": "<descriptive>", "provider": "Microsoft.Authorization", "type": "Microsoft.Authorization/policyDefinitions" },
  { "name": "Application Insights", "abbreviation": "appi", "provider": "Microsoft.Insights", "type": "Microsoft.Insights/components" },
  { "name": "Azure Monitor action group", "abbreviation": "ag", "provider": "Microsoft.Insights", "type": "Microsoft.Insights/actionGroups" },
  { "name": "Azure Monitor data collection rule", "abbreviation": "dcr", "provider": "Microsoft.Insights", "type": "Microsoft.Insights/dataCollectionRules" },
  { "name": "Azure Monitor alert processing rule", "abbreviation": "apr", "provider": "Microsoft.AlertsManagement", "type": "Microsoft.AlertsManagement/actionRules" },
  { "name": "Blueprint (planned for deprecation)", "abbreviation": "bp", "provider": "Microsoft.Blueprint", "type": "Microsoft.Blueprint/blueprints" },
  { "name": "Blueprint assignment (planned for deprecation)", "abbreviation": "bpa", "provider": "Microsoft.Blueprint", "type": "Microsoft.Blueprint/blueprints/artifacts" },
  { "name": "Data collection endpoint", "abbreviation": "dce", "provider": "Microsoft.Insights", "type": "Microsoft.Insights/dataCollectionEndpoints" },
  { "name": "Log Analytics workspace", "abbreviation": "log", "provider": "Microsoft.OperationalInsights", "type": "Microsoft.OperationalInsights/workspaces" },
  { "name": "Log Analytics query packs", "abbreviation": "pack", "provider": "Microsoft.OperationalInsights", "type": "Microsoft.OperationalInsights/querypacks" },
  { "name": "Management group", "abbreviation": "mg", "provider": "Microsoft.Management", "type": "Microsoft.Management/managementGroups" },
  { "name": "Microsoft Purview instance", "abbreviation": "pview", "provider": "Microsoft.Purview", "type": "Microsoft.Purview/accounts" },
  { "name": "Resource group", "abbreviation": "rg", "provider": "Microsoft.Resources", "type": "Microsoft.Resources/resourceGroups" },
  { "name": "Template specs name", "abbreviation": "ts", "provider": "Microsoft.Resources", "type": "Microsoft.Resources/templateSpecs" },
  { "name": "Azure Migrate project", "abbreviation": "migr", "provider": "Microsoft.Migrate", "type": "Microsoft.Migrate/assessmentProjects" },
  { "name": "Database Migration Service instance", "abbreviation": "dms", "provider": "Microsoft.DataMigration", "type": "Microsoft.DataMigration/services" },
  { "name": "Recovery Services vault", "abbreviation": "rsv", "provider": "Microsoft.RecoveryServices", "type": "Microsoft.RecoveryServices/vaults" },
  { "name": "Application gateway", "abbreviation": "agw", "provider": "Microsoft.Network", "type": "Microsoft.Network/applicationGateways" },
  { "name": "Application security group (ASG)", "abbreviation": "asg", "provider": "Microsoft.Network", "type": "Microsoft.Network/applicationSecurityGroups" },
  { "name": "CDN profile", "abbreviation": "cdnp", "provider": "Microsoft.Cdn", "type": "Microsoft.Cdn/profiles" },
  { "name": "CDN endpoint", "abbreviation": "cdne", "provider": "Microsoft.Cdn", "type": "Microsoft.Cdn/profiles/endpoints" },
  { "name": "Connections", "abbreviation": "con", "provider": "Microsoft.Network", "type": "Microsoft.Network/connections" },
  { "name": "DNS", "abbreviation": "<DNS domain name>", "provider": "Microsoft.Network", "type": "Microsoft.Network/dnsZones" },
  { "name": "DNS forwarding ruleset", "abbreviation": "dnsfrs", "provider": "Microsoft.Network", "type": "Microsoft.Network/dnsForwardingRulesets" },
  { "name": "DNS private resolver", "abbreviation": "dnspr", "provider": "Microsoft.Network", "type": "Microsoft.Network/dnsResolvers" },
  { "name": "DNS private resolver inbound endpoint", "abbreviation": "in", "provider": "Microsoft.Network", "type": "Microsoft.Network/dnsResolvers/inboundEndpoints" },
  { "name": "DNS private resolver outbound endpoint", "abbreviation": "out", "provider": "Microsoft.Network", "type": "Microsoft.Network/dnsResolvers/outboundEndpoints" },
  { "name": "DNS zone", "abbreviation": "<DNS domain name>", "provider": "Microsoft.Network", "type": "Microsoft.Network/privateDnsZones" },
  { "name": "Firewall", "abbreviation": "afw", "provider": "Microsoft.Network", "type": "Microsoft.Network/azureFirewalls" },
  { "name": "Firewall policy", "abbreviation": "afwp", "provider": "Microsoft.Network", "type": "Microsoft.Network/firewallPolicies" },
  { "name": "ExpressRoute circuit", "abbreviation": "erc", "provider": "Microsoft.Network", "type": "Microsoft.Network/expressRouteCircuits" },
  { "name": "ExpressRoute direct", "abbreviation": "erd", "provider": "Microsoft.Network", "type": "Microsoft.Network/expressRoutePorts" },
  { "name": "ExpressRoute gateway", "abbreviation": "ergw", "provider": "Microsoft.Network", "type": "Microsoft.Network/virtualNetworkGateways" },
  { "name": "Front Door (Standard/Premium) profile", "abbreviation": "afd", "provider": "Microsoft.Cdn", "type": "Microsoft.Cdn/profiles" },
  { "name": "Front Door (Standard/Premium) endpoint", "abbreviation": "fde", "provider": "Microsoft.Cdn", "type": "Microsoft.Cdn/profiles/afdEndpoints" },
  { "name": "Front Door firewall policy", "abbreviation": "fdfp", "provider": "Microsoft.Network", "type": "Microsoft.Network/frontdoorWebApplicationFirewallPolicies" },
  { "name": "Front Door (classic)", "abbreviation": "afd", "provider": "Microsoft.Network", "type": "Microsoft.Network/frontDoors" },
  { "name": "IP group", "abbreviation": "ipg", "provider": "Microsoft.Network", "type": "Microsoft.Network/ipGroups" },
  { "name": "Load balancer (internal)", "abbreviation": "lbi", "provider": "Microsoft.Network", "type": "Microsoft.Network/loadBalancers" },
  { "name": "Load balancer (external)", "abbreviation": "lbe", "provider": "Microsoft.Network", "type": "Microsoft.Network/loadBalancers" },
  { "name": "Load balancer rule", "abbreviation": "rule", "provider": "Microsoft.Network", "type": "Microsoft.Network/loadBalancers/inboundNatRules" },
  { "name": "Local network gateway", "abbreviation": "lgw", "provider": "Microsoft.Network", "type": "Microsoft.Network/localNetworkGateways" },
  { "name": "NAT gateway", "abbreviation": "ng", "provider": "Microsoft.Network", "type": "Microsoft.Network/natGateways" },
  { "name": "Network interface (NIC)", "abbreviation": "nic", "provider": "Microsoft.Network", "type": "Microsoft.Network/networkInterfaces" },
  { "name": "Network security group (NSG)", "abbreviation": "nsg", "provider": "Microsoft.Network", "type": "Microsoft.Network/networkSecurityGroups" },
  { "name": "Network security group (NSG) security rules", "abbreviation": "nsgsr", "provider": "Microsoft.Network", "type": "Microsoft.Network/networkSecurityGroups/securityRules" },
  { "name": "Network Watcher", "abbreviation": "nw", "provider": "Microsoft.Network", "type": "Microsoft.Network/networkWatchers" },
  { "name": "Private Link", "abbreviation": "pl", "provider": "Microsoft.Network", "type": "Microsoft.Network/privateLinkServices" },
  { "name": "Private endpoint", "abbreviation": "pep", "provider": "Microsoft.Network", "type": "Microsoft.Network/privateEndpoints" },
  { "name": "Public IP address", "abbreviation": "pip", "provider": "Microsoft.Network", "type": "Microsoft.Network/publicIPAddresses" },
  { "name": "Public IP address prefix", "abbreviation": "ippre", "provider": "Microsoft.Network", "type": "Microsoft.Network/publicIPPrefixes" },
  { "name": "Route filter", "abbreviation": "rf", "provider": "Microsoft.Network", "type": "Microsoft.Network/routeFilters" },
  { "name": "Route server", "abbreviation": "rtserv", "provider": "Microsoft.Network", "type": "Microsoft.Network/virtualHubs" },
  { "name": "Route table", "abbreviation": "rt", "provider": "Microsoft.Network", "type": "Microsoft.Network/routeTables" },
  { "name": "Service endpoint policy", "abbreviation": "se", "provider": "Microsoft.Network", "type": "Microsoft.Network/serviceEndPointPolicies" },
  { "name": "Traffic Manager profile", "abbreviation": "traf", "provider": "Microsoft.Network", "type": "Microsoft.Network/trafficManagerProfiles" },
  { "name": "User defined route (UDR)", "abbreviation": "udr", "provider": "Microsoft.Network", "type": "Microsoft.Network/routeTables/routes" },
  { "name": "Virtual network", "abbreviation": "vnet", "provider": "Microsoft.Network", "type": "Microsoft.Network/virtualNetworks" },
  { "name": "Virtual network gateway", "abbreviation": "vgw", "provider": "Microsoft.Network", "type": "Microsoft.Network/virtualNetworkGateways" },
  { "name": "Virtual network manager", "abbreviation": "vnm", "provider": "Microsoft.Network", "type": "Microsoft.Network/networkManagers" },
  { "name": "Virtual network peering", "abbreviation": "peer", "provider": "Microsoft.Network", "type": "Microsoft.Network/virtualNetworks/virtualNetworkPeerings" },
  { "name": "Virtual network subnet", "abbreviation": "snet", "provider": "Microsoft.Network", "type": "Microsoft.Network/virtualNetworks/subnets" },
  { "name": "Virtual WAN", "abbreviation": "vwan", "provider": "Microsoft.Network", "type": "Microsoft.Network/virtualWans" },
  { "name": "Virtual WAN Hub", "abbreviation": "vhub", "provider": "Microsoft.Network", "type": "Microsoft.Network/virtualHubs" },
  { "name": "Azure Bastion", "abbreviation": "bas", "provider": "Microsoft.Network", "type": "Microsoft.Network/bastionHosts" },
  { "name": "Key vault", "abbreviation": "kv", "provider": "Microsoft.KeyVault", "type": "Microsoft.KeyVault/vaults" },
  { "name": "Key Vault Managed HSM", "abbreviation": "kvmhsm", "provider": "Microsoft.KeyVault", "type": "Microsoft.KeyVault/managedHSMs" },
  { "name": "Managed identity", "abbreviation": "id", "provider": "Microsoft.ManagedIdentity", "type": "Microsoft.ManagedIdentity/userAssignedIdentities" },
  { "name": "SSH key", "abbreviation": "sshkey", "provider": "Microsoft.Compute", "type": "Microsoft.Compute/sshPublicKeys" },
  { "name": "VPN Gateway", "abbreviation": "vpng", "provider": "Microsoft.Network", "type": "Microsoft.Network/vpnGateways" },
  { "name": "VPN connection", "abbreviation": "vcn", "provider": "Microsoft.Network", "type": "Microsoft.Network/vpnGateways/vpnConnections" },
  { "name": "VPN site", "abbreviation": "vst", "provider": "Microsoft.Network", "type": "Microsoft.Network/vpnGateways/vpnSites" },
  { "name": "Web Application Firewall (WAF) policy", "abbreviation": "waf", "provider": "Microsoft.Network", "type": "Microsoft.Network/firewallPolicies" },
  { "name": "Web Application Firewall (WAF) policy rule group", "abbreviation": "wafrg", "provider": "Microsoft.Network", "type": "Microsoft.Network/firewallPolicies/ruleGroups" },
  { "name": "Azure StorSimple", "abbreviation": "ssimp", "provider": "Microsoft.StorSimple", "type": "Microsoft.StorSimple/managers" },
  { "name": "Backup Vault name", "abbreviation": "bvault", "provider": "Microsoft.DataProtection", "type": "Microsoft.DataProtection/backupVaults" },
  { "name": "Backup Vault policy", "abbreviation": "bkpol", "provider": "Microsoft.DataProtection", "type": "Microsoft.DataProtection/backupVaults/backupPolicies" },
  { "name": "File share", "abbreviation": "share", "provider": "Microsoft.Storage", "type": "Microsoft.Storage/storageAccounts/fileServices/shares" },
  { "name": "Storage account", "abbreviation": "st", "provider": "Microsoft.Storage", "type": "Microsoft.Storage/storageAccounts" },
  { "name": "Storage Sync Service name", "abbreviation": "sss", "provider": "Microsoft.StorageSync", "type": "Microsoft.StorageSync/storageSyncServices" },
  { "name": "Virtual desktop host pool", "abbreviation": "vdpool", "provider": "Microsoft.DesktopVirtualization", "type": "Microsoft.DesktopVirtualization/hostPools" },
  { "name": "Virtual desktop application group", "abbreviation": "vdag", "provider": "Microsoft.DesktopVirtualization", "type": "Microsoft.DesktopVirtualization/applicationGroups" },
  { "name": "Virtual desktop workspace", "abbreviation": "vdws", "provider": "Microsoft.DesktopVirtualization", "type": "Microsoft.DesktopVirtualization/workspaces" },
  { "name": "Virtual desktop scaling plan", "abbreviation": "vdscaling", "provider": "Microsoft.DesktopVirtualization", "type": "Microsoft.DesktopVirtualization/scalingPlans" }
];
  
  export default resources;  