const resources = [
  { name: "AI Search", abbreviation: "srch" },
  { name: "Azure AI Services", abbreviation: "ais" },
  { name: "Azure AI Studio Hub", abbreviation: "hub" },
  { name: "Azure AI Studio Project", abbreviation: "proj" },
  { name: "Azure AI Video Indexer", abbreviation: "avi" },
  { name: "Azure Machine Learning Workspace", abbreviation: "mlw" },
  { name: "Azure OpenAI Service", abbreviation: "oai" },
  { name: "Bot Service", abbreviation: "bot" },
  { name: "Computer Vision", abbreviation: "cv" },
  { name: "Content Moderator", abbreviation: "cm" },
  { name: "Content Safety", abbreviation: "cs" },
  { name: "API Management", abbreviation: "apim" },
  { name: "App Service Plan", abbreviation: "asp" },
  { name: "App Service Web App", abbreviation: "web" },
  { name: "App Service Functions", abbreviation: "func" },
  { name: "Application Gateway", abbreviation: "agw" },
  { name: "Application Insights", abbreviation: "ai" },
  { name: "Application Security Group", abbreviation: "asg" },
  { name: "Application Service Environment", abbreviation: "ase" },
  { name: "Automation Account", abbreviation: "aa" },
  { name: "Availability Set", abbreviation: "as" },
  { name: "Azure Cache for Redis", abbreviation: "redis" },
  { name: "CDN Profile", abbreviation: "cdn" },
  { name: "Cognitive Services Account", abbreviation: "cogs" },
  { name: "Container Registry", abbreviation: "cr" },
  { name: "Cosmos DB", abbreviation: "cos" },
  { name: "Event Hubs Namespace", abbreviation: "eh" },
  { name: "Gateway Connection", abbreviation: "cn" },
  { name: "Key Vault", abbreviation: "kv" },
  { name: "Load Balancer", abbreviation: "lb" },
  { name: "Log Analytics Workspace", abbreviation: "la" },
  { name: "Logic App", abbreviation: "lapp" },
  { name: "Machine Learning Workspace", abbreviation: "ml" },
  { name: "Network Interface", abbreviation: "nic" },
  { name: "Network Security Group", abbreviation: "nsg" },
  { name: "Notification Hub Namespace", abbreviation: "nh" },
  { name: "Public IP Address", abbreviation: "pip" },
  { name: "Resource Group", abbreviation: "rg" },
  { name: "Route Table", abbreviation: "rt" },
  { name: "Search Service", abbreviation: "srch" },
  { name: "Service Bus Namespace", abbreviation: "sbus" },
  { name: "SQL Server Managed Instance", abbreviation: "sqlmi" },
  { name: "SQL Database", abbreviation: "sql" },
  { name: "Storage Account", abbreviation: "st" },
  { name: "Traffic Manager Profile", abbreviation: "tm" },
  { name: "Virtual Machine", abbreviation: "vm" },
  { name: "Virtual Network Gateway", abbreviation: "gw" },
  { name: "Virtual Network", abbreviation: "vnet" },
];
  
  export default resources;  