const resources = [
  { name: "AI Search", abbreviation: "srch" },
  { name: "Azure AI Services", abbreviation: "ais" },
  { name: "Azure AI Studio Hub", abbreviation: "hub" },
  { name: "Azure AI Studio Project", abbreviation: "proj" },
  { name: "Azure AI Video Indexer", abbreviation: "avi" },
  { name: "Azure Machine Learning Workspace", abbreviation: "mlw" },
  { name: "Azure OpenAI Service", abbreviation: "oai" },
  { name: "Bot Service", abbreviation: "bot" },
  { name: "Computer Vision", abbreviation: "cv" },
  { name: "Content Moderator", abbreviation: "cm" },
  { name: "Content Safety", abbreviation: "cs" },
  { name: "API Management", abbreviation: "apim" },
  { name: "App Service Plan", abbreviation: "asp" },
  { name: "App Service Web App", abbreviation: "web" },
  { name: "App Service Functions", abbreviation: "func" },
  { name: "Application Gateway", abbreviation: "agw" },
  { name: "Application Insights", abbreviation: "ai" },
  { name: "Application Security Group", abbreviation: "asg" },
  { name: "Application Service Environment", abbreviation: "ase" },
  { name: "Automation Account", abbreviation: "aa" },
  { name: "Availability Set", abbreviation: "as" },
  { name: "Azure Cache for Redis", abbreviation: "redis" },
  { name: "CDN Profile", abbreviation: "cdn" },
  { name: "Cognitive Services Account", abbreviation: "cogs" },
  { name: "Container Registry", abbreviation: "cr" },
  { name: "Cosmos DB", abbreviation: "cos" },
  { name: "Event Hubs Namespace", abbreviation: "eh" },
  { name: "Gateway Connection", abbreviation: "cn" },
  { name: "Key Vault", abbreviation: "kv" },
  { name: "Load Balancer", abbreviation: "lb" },
  { name: "Log Analytics Workspace", abbreviation: "la" },
  { name: "Logic App", abbreviation: "lapp" },
  { name: "Machine Learning Workspace", abbreviation: "ml" },
  { name: "Network Interface", abbreviation: "nic" },
  { name: "Network Security Group", abbreviation: "nsg" },
  { name: "Notification Hub Namespace", abbreviation: "nh" },
  { name: "Public IP Address", abbreviation: "pip" },
  { name: "Resource Group", abbreviation: "rg" },
  { name: "Route Table", abbreviation: "rt" },
  { name: "Search Service", abbreviation: "srch" },
  { name: "Service Bus Namespace", abbreviation: "sbus" },
  { name: "SQL Server Managed Instance", abbreviation: "sqlmi" },
  { name: "SQL Database", abbreviation: "sql" },
  { name: "Storage Account", abbreviation: "st" },
  { name: "Traffic Manager Profile", abbreviation: "tm" },
  { name: "Virtual Machine", abbreviation: "vm" },
  { name: "Virtual Network Gateway", abbreviation: "gw" },
  { name: "Virtual Network", abbreviation: "vnet" },
  { name: "Azure Blob Storage", abbreviation: "st" },
  { name: "Azure Kubernetes Service", abbreviation: "aks" },
  { name: "Azure Data Lake Storage", abbreviation: "dls" },
  { name: "Azure Synapse Analytics", abbreviation: "syn" },
  { name: "Azure Data Factory", abbreviation: "df" },
  { name: "Azure HDInsight", abbreviation: "hdi" },
  { name: "Azure Stream Analytics", abbreviation: "asa" },
  { name: "Azure Event Grid", abbreviation: "eg" },
  { name: "Azure Firewall", abbreviation: "afw" },
  { name: "Azure Front Door", abbreviation: "afd" },
  { name: "Azure Private Link", abbreviation: "pl" },
  { name: "Azure Service Fabric Cluster", abbreviation: "sfc" },
  { name: "Azure SignalR Service", abbreviation: "sr" },
  { name: "Azure Virtual WAN", abbreviation: "vwan" },
  { name: "Azure Bastion", abbreviation: "bas" },
  { name: "Azure Dedicated Host", abbreviation: "dh" },
  { name: "Azure Disk Storage", abbreviation: "disk" },
  { name: "Azure File Storage", abbreviation: "file" },
  { name: "Azure NetApp Files", abbreviation: "anf" },
  { name: "Azure Queue Storage", abbreviation: "queue" },
  { name: "Azure Table Storage", abbreviation: "table" },
  { name: "Azure VPN Gateway", abbreviation: "vpngw" },
  { name: "Azure ExpressRoute", abbreviation: "er" },
  { name: "Azure DDoS Protection", abbreviation: "ddos" },
  { name: "Azure Policy", abbreviation: "policy" },
  { name: "Azure Blueprints", abbreviation: "bp" },
  { name: "Azure Security Center", abbreviation: "asc" },
  { name: "Azure Sentinel", abbreviation: "sentinel" },
  { name: "Azure Key Vault Managed HSM", abbreviation: "hsm" },
  { name: "Azure DevTest Labs", abbreviation: "dtl" },
  { name: "Azure Lab Services", abbreviation: "lab" },
  { name: "Azure VMware Solution", abbreviation: "avs" },
  { name: "Azure Arc", abbreviation: "arc" },
  { name: "Azure Lighthouse", abbreviation: "lh" },
  { name: "Azure Monitor", abbreviation: "mon" },
  { name: "Azure Advisor", abbreviation: "adv" },
  { name: "Azure Automation", abbreviation: "aa" },
  { name: "Azure Backup", abbreviation: "backup" },
  { name: "Azure Site Recovery", abbreviation: "asr" },
  { name: "Azure Migrate", abbreviation: "migrate" },
  { name: "Azure Data Box", abbreviation: "dbox" },
  { name: "Azure Stack Edge", abbreviation: "ase" },
  { name: "Azure Stack HCI", abbreviation: "hci" },
  { name: "Azure Stack Hub", abbreviation: "ash" },
];
  
  export default resources;  